project_id = "dpm-fipp-unima-greenfield"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[auth]
enabled = true
site_url = "https://dpmfippunima.vercel.app"
additional_redirect_urls = ["https://dpmfippunima.vercel.app/aktivasi", "http://localhost:3000/aktivasi", "http://localhost:3000/auth/callback"]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage]
enabled = true
