export type Publication = { slug:string; type:string; title:string; summary:string; date:string; body:string[]; tags:string[] };
export const publications:Publication[]=[
  {slug:'kajian-biaya-pendidikan-2026',type:'D-SIGHT',title:'Kajian biaya pendidikan dan akses layanan akademik 2026',summary:'Analisis aspirasi mahasiswa tentang transparansi biaya, layanan akademik, dan rekomendasi kebijakan.',date:'29 Agustus 2026',body:['Kajian ini merangkum tema aspirasi mahasiswa mengenai biaya pendidikan, akses informasi, dan kualitas layanan akademik. Data contoh pada preview ini bersifat sintetis dan belum merupakan publikasi resmi hasil penelitian.','Rekomendasi final wajib melalui alur editorial, review sumber, pemeriksaan aksesibilitas, dan persetujuan pemilik konten sebelum berstatus published.'],tags:['pendidikan','layanan akademik']},
  {slug:'rapat-dengar-pendapat-agustus-2026',type:'BERITA',title:'Rapat dengar pendapat mahasiswa FIPP: rangkuman dan tindak lanjut',summary:'Rangkuman pembahasan, komitmen unit terkait, serta jadwal evaluasi terbuka.',date:'27 Agustus 2026',body:['Rapat dengar pendapat menjadi ruang untuk memetakan kebutuhan mahasiswa dan menetapkan tindak lanjut yang dapat diperiksa.','Setiap komitmen harus memiliki pemilik, tanggal target, status, dan catatan koreksi bila terjadi perubahan.'],tags:['aspirasi','rapat']},
  {slug:'laporan-pengawasan-semester-ganjil',type:'D-TRACE',title:'Laporan pengawasan program kerja organisasi mahasiswa semester ganjil',summary:'Temuan, progres, dan catatan tindak lanjut pengawasan program kerja.',date:'24 Agustus 2026',body:['D-TRACE menyajikan ringkasan pengawasan yang aman untuk publik tanpa membuka catatan internal atau data personal.','Temuan dan tindak lanjut dikelola dengan histori revisi agar perubahan substantif tetap dapat ditelusuri.'],tags:['pengawasan','ormawa']},
  {slug:'keputusan-sidang-pleno-agustus-2026',type:'D-DAR',title:'Arsip keputusan sidang pleno periode Agustus 2026',summary:'Dokumen keputusan, daftar hadir, dan ringkasan agenda sidang.',date:'20 Agustus 2026',body:['Arsip kelembagaan membantu kesinambungan antarperiode dan menjadi rujukan keputusan yang telah disahkan.','Dokumen publik harus telah diklasifikasi, diperiksa hak aksesnya, dan memiliki metadata retensi.'],tags:['arsip','sidang']},
  {slug:'kalender-konsultasi-september',type:'PROGRAM',title:'Kalender konsultasi dan serap aspirasi September',summary:'Jadwal kunjungan unit dan ruang dialog terbuka bersama mahasiswa.',date:'18 Agustus 2026',body:['Agenda konsultasi memberi pilihan kanal partisipasi selain D-DAS. Aspirasi sensitif tetap diarahkan ke layanan privat.'],tags:['program','konsultasi']},
  {slug:'struktur-penanggung-jawab-unit',type:'BERITA',title:'Pembaruan struktur dan penanggung jawab unit DPM',summary:'Susunan unit, mandat, dan kanal komunikasi resmi periode berjalan.',date:'14 Agustus 2026',body:['Struktur, unit, posisi, dan masa berlaku kepengurusan dikelola sebagai data periode sehingga perubahan rutin tidak membutuhkan redeploy.'],tags:['struktur','unit']},
];
export function findPublication(slug:string){return publications.find((item)=>item.slug===slug)}
