'use client';
import { useEffect, useState } from 'react';
import { ShieldCheck } from 'lucide-react';
type Factor={id:string;factor_type:string;status:string};
export function AdminMfaForm(){const[factor,setFactor]=useState<Factor|null>(null);const[qr,setQr]=useState('');const[secret,setSecret]=useState('');const[error,setError]=useState('');const[loading,setLoading]=useState(true);
 useEffect(()=>{void(async()=>{try{const response=await fetch('/api/admin/auth/session',{cache:'no-store'});const result=await response.json() as {ok:boolean;aal?:string;factors?:Factor[]};if(!response.ok)throw new Error('Sesi login tidak ditemukan.');if(result.aal==='aal2'){window.location.assign('/admin/dashboard');return}const verified=result.factors?.find((item)=>item.factor_type==='totp'&&item.status==='verified');if(verified){setFactor(verified);return}const enroll=await fetch('/api/admin/auth/mfa',{method:'POST'});const enrolled=await enroll.json() as {ok:boolean;data?:{id:string;qrCode:string;secret:string};message?:string};if(!enroll.ok||!enrolled.data)throw new Error(enrolled.message??'MFA belum dapat disiapkan.');setFactor({id:enrolled.data.id,factor_type:'totp',status:'unverified'});setQr(enrolled.data.qrCode);setSecret(enrolled.data.secret)}catch(reason){setError(reason instanceof Error?reason.message:'MFA belum tersedia.')}finally{setLoading(false)}})()},[]);
 return <form className="admin-auth-card" onSubmit={async(event)=>{event.preventDefault();setError('');const code=new FormData(event.currentTarget).get('code');if(!factor)return;const response=await fetch('/api/admin/auth/mfa',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({factorId:factor.id,challengeId:'00000000-0000-0000-0000-000000000000',code})});const result=await response.json() as {ok:boolean;message?:string};if(response.ok&&result.ok)window.location.assign('/admin/dashboard');else setError(result.message??'Kode tidak valid.')}}>
  <span className="admin-auth-icon"><ShieldCheck/></span><p className="form-eyebrow">VERIFIKASI AAL2</p><h1>Amankan sesi admin</h1><p>{factor?.status==='verified'?'Masukkan enam digit dari aplikasi authenticator.':'Pindai QR atau masukkan secret ke aplikasi authenticator, lalu masukkan enam digit.'}</p>{loading&&<p>Menyiapkan authenticator…</p>}{qr&&<img className="mfa-qr" src={qr} alt="QR pendaftaran authenticator"/>}{secret&&<code className="mfa-secret">{secret}</code>}{error&&<div role="alert" className="form-error-summary">{error}</div>}
  <label htmlFor="mfa-code">Kode enam digit</label><input id="mfa-code" name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} required disabled={!factor}/><button className="native-button" type="submit" disabled={!factor}>Verifikasi dan masuk</button>
 </form>}

