'use client';

import { useState } from 'react';
import { CheckCircle2, Circle, LockKeyhole, Search } from 'lucide-react';

type Result = { ticket:string; status:string; submittedAt:string; timeline:Array<{state:string;message:string;occurredAt:string}> };
type ApiResult = { ok:boolean; data?:Result; message?:string; requestId:string };
const labels:Record<string,string>={received:'Aspirasi diterima',triaged:'Peninjauan awal',assigned:'Ditugaskan ke unit terkait',in_progress:'Sedang ditangani',waiting_for_information:'Menunggu informasi',resolved:'Penanganan selesai',closed:'Kasus ditutup',rejected_out_of_scope:'Di luar cakupan',reopened:'Dibuka kembali'};

export function TrackingForm() {
  const [result,setResult]=useState<Result|null>(null); const [error,setError]=useState(''); const [pending,setPending]=useState(false);
  return <div className="tracking-card"><form onSubmit={async(event)=>{event.preventDefault();setError('');setResult(null);setPending(true);const data=new FormData(event.currentTarget);try{const response=await fetch('/api/ddas/track',{method:'POST',headers:{'Content-Type':'application/json'},cache:'no-store',body:JSON.stringify({ticket:String(data.get('ticket')??''),secret:String(data.get('secret')??'')})});const payload=await response.json() as ApiResult;if(!response.ok||!payload.ok||!payload.data)throw new Error(payload.message??'Kode tidak dapat diverifikasi.');setResult(payload.data)}catch(reason){setError(reason instanceof Error?reason.message:'Kode tidak dapat diverifikasi.')}finally{setPending(false)}}}><label htmlFor="ticket">Nomor tiket</label><input id="ticket" name="ticket" required placeholder="D-DAS-2026-XXXXXXXXXXXXXXXXXXXX" autoComplete="off" /><label htmlFor="secret">Kode pelacakan privat</label><input id="secret" name="secret" required placeholder="Kode dari receipt" type="password" autoComplete="off" minLength={32} /><button className="native-button" type="submit" disabled={pending}><Search /> {pending?'Memverifikasi…':'Periksa status'}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>{result&&<div className="tracking-result" aria-live="polite"><p className="form-eyebrow">STATUS TERKINI</p><h2>{labels[result.status]??result.status}</h2><p>Tiket <b>{result.ticket}</b> berhasil diverifikasi.</p><div className="timeline">{result.timeline.map((item,index)=><div className="done" key={`${item.state}-${item.occurredAt}`}><CheckCircle2 /><span><b>{labels[item.state]??item.state}</b><small>{item.message} · {new Date(item.occurredAt).toLocaleDateString('id-ID',{dateStyle:'long'})}</small></span></div>)}{result.status!=='closed'&&<div><Circle /><span><b>Langkah berikutnya</b><small>Pembaruan berikutnya akan tampil setelah ditinjau dan disanitasi.</small></span></div>}</div></div>}<p className="tracking-security"><LockKeyhole /> Respons bersifat private/no-store dan tidak masuk analytics atau indeks publik.</p></div>;
}
