import Link from 'next/link';
import { ArrowRight, BarChart3, BookOpen, Building2, Check, FileText, FolderArchive, Gavel, Megaphone, Send, ShieldCheck, Users } from 'lucide-react';
import { PublicHeader } from './public-header';
import { PublicFooter } from './public-footer';
import { DdasForm } from './ddas-form';
import { TrackingForm } from './tracking-form';
import { PublicComments } from './public-comments';

const campusImage='/fipp-campus-hero.png';
const activityImages=[
 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=80',
 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80',
 'https://images.unsplash.com/photo-1553877522-43269d4ea984?auto=format&fit=crop&w=900&q=80',
 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80',
 'https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=900&q=80',
 'https://images.unsplash.com/photo-1456324504439-367cee3b3c32?auto=format&fit=crop&w=900&q=80',
];

function PublicCta(){return <section className="v4-public-cta"><div><Users/><span><b>DPM hadir untuk mendengar, mewakili, dan mengawal setiap aspirasi mahasiswa.</b><small>Bersama membangun FIPP yang lebih baik.</small></span></div><Link href="/ddas"><Send/> Kirim Aspirasi Sekarang</Link></section>}
function PublicFrame({children}:{children:React.ReactNode}){return <main className="v4-public"><PublicHeader/>{children}<div className="v4-shell"><PublicCta/></div><PublicFooter/></main>}

export function V4Home(){const cards=[
 {icon:BookOpen,title:'Berita Terbaru',big:'3',copy:'Forum aspirasi dan rapat paripurna terbaru',href:'/berita'},
 {icon:BarChart3,title:'D-DAS',big:'5',copy:'3 dalam proses · 1 ditindaklanjuti · 1 selesai',href:'/ddas'},
 {icon:FileText,title:'Kajian & Transparansi',big:'3',copy:'Laporan kinerja, notulen, dan laporan keuangan',href:'/transparansi'},
 {icon:Gavel,title:'Program Kerja',big:'13',copy:'65% progres rata-rata semua program',href:'/program'},
 {icon:Building2,title:'ORMAWA FIPP',big:'12',copy:'Organisasi mahasiswa aktif dan terverifikasi',href:'/ormawa'},
 ]; return <PublicFrame><section className="v4-home-hero" style={{'--campus':`url(${campusImage})`} as React.CSSProperties}><div className="v4-shell"><div className="v4-hero-copy"><span>DEWAN PERWAKILAN MAHASISWA</span><h1>DPM FIPP UNIMA</h1><h2>Representasi, Aspirasi, Legislasi,<br/>dan Pengawasan Mahasiswa.</h2><p>DPM FIPP UNIMA hadir sebagai jembatan komunikasi antara mahasiswa dan fakultas untuk mendorong perubahan, transparansi, dan kemajuan bersama.</p><div><Link href="/tentang"><ShieldCheck/> Jelajahi DPM</Link><Link href="/ddas"><Send/> Kirim Aspirasi</Link></div></div></div></section><section className="v4-shell v4-home-cards">{cards.map((c)=><article key={c.title}><header><span><c.icon/></span><b>{c.title}</b><Link href={c.href}>Lihat semua</Link></header><strong>{c.big}</strong><p>{c.copy}</p><Link href={c.href}>Lihat selengkapnya <ArrowRight/></Link></article>)}</section></PublicFrame>}

export function V4About(){const units=['Komisi 1 — Legislasi & Kebijakan','Komisi 2 — Pengawasan & Advokasi','Humas — Hubungan Masyarakat','Media & Informasi','PSDM','Keuangan'];return <PublicFrame><section className="v4-about-hero" style={{'--campus':`url(${campusImage})`} as React.CSSProperties}><div className="v4-shell"><small>Beranda　›　Tentang</small><h1>Tentang DPM FIPP UNIMA</h1><h2>Representasi, Aspirasi, Legislasi, dan Pengawasan Mahasiswa.</h2><p>DPM FIPP UNIMA hadir sebagai jembatan komunikasi antara mahasiswa dan fakultas untuk mendorong perubahan, transparansi, dan kemajuan bersama.</p><div className="v4-period"><span>Berdiri Sejak<b>2006</b></span><span>Periode Aktif<b>2026–2027</b></span></div></div></section><section className="v4-shell v4-org"><header><h2>Struktur Organisasi DPM FIPP UNIMA</h2><p>Struktur organisasi bersifat dinamis dan dapat berubah setiap periode kepengurusan.</p></header><div className="v4-org-top"><article><Users/><b>Ketua Umum</b><small>Chairperson</small></article><article><Users/><b>Sekretaris Umum</b><small>Secretary General</small></article></div><div className="v4-org-units">{units.map(x=><article key={x}><ShieldCheck/><b>{x.split(' — ')[0]}</b><small>{x.split(' — ')[1]}</small></article>)}</div><div className="v4-about-cards"><article><h3>Unit DPM</h3><p>Unit kerja dapat berubah setiap periode sesuai kebutuhan organisasi.</p><span>Komisi　 Badan Kerja　 Tim Ad-hoc</span></article><article><h3>Visi & Misi</h3><p>Menjadi lembaga representatif, aspiratif, dan akuntabel dalam mewujudkan mahasiswa FIPP UNIMA yang kritis dan kolaboratif.</p><ul><li><Check/>Menyalurkan aspirasi secara efektif.</li><li><Check/>Mengawal kebijakan yang berpihak.</li><li><Check/>Menjaga transparansi organisasi.</li></ul></article><article><h3>ORMAWA / Organisasi Mitra</h3><p>Bersinergi untuk membangun FIPP UNIMA yang lebih baik.</p><div className="v4-logo-row">{[1,2,3,4,5,6].map(i=><span key={i}><Building2/></span>)}</div></article></div></section></PublicFrame>}

const publications=[
 ['BERITA','DPM FIPP UNIMA Gelar Forum Aspirasi Mahasiswa Periode 2026–2027','Forum aspirasi menjadi ruang dialog terbuka antara mahasiswa dan pimpinan fakultas.'],
 ['KAJIAN','Evaluasi Efektivitas Kurikulum MBKM di FIPP UNIMA','Kajian implementasi MBKM dan rekomendasi perbaikan.'],
 ['D-SIGHT','Potret Aspirasi Mahasiswa April 2026','Ringkasan data aspirasi mahasiswa berdasarkan topik dan status.'],
 ['D-TRACE','Tindak Lanjut Aspirasi Periode Maret–April 2026','Laporan progres tindak lanjut aspirasi bersama unit terkait.'],
 ['MEDIA','Diskusi Publik: Pendidikan Inklusif dan Berkelanjutan','Dokumentasi kegiatan diskusi publik bersama narasumber dan mahasiswa.'],
 ['ARSIP','Laporan Kinerja DPM Periode 2025','Dokumen laporan kinerja sebagai bentuk akuntabilitas organisasi.'],
];
export function V4Publications(){return <PublicFrame><section className="v4-publication-hero" style={{'--campus':`url(${campusImage})`} as React.CSSProperties}><div className="v4-shell"><small>⌂　Beranda　›　Publikasi, Kajian & Media</small><h1>Publikasi, Kajian & Media</h1><p>Akses berbagai informasi resmi, hasil kajian, laporan, data, hingga dokumentasi kegiatan DPM FIPP UNIMA.</p></div></section><section className="v4-shell"><div className="v4-pub-filters">{['Jenis Konten','Kategori','Unit','Periode','Sortir'].map(x=><label key={x}><span>{x}</span><select><option>Semua {x}</option></select></label>)}<label><span>Pencarian</span><input placeholder="Cari publikasi, kajian, d-sight..."/></label><div>{['Semua','Berita','Kajian','D-SIGHT','D-TRACE','Media','Arsip'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</div></div><div className="v4-pub-grid">{publications.map((p,i)=><article key={p[1]}><div style={{backgroundImage:`url(${activityImages[i]})`}}><span>{p[0]}</span></div><small>{12-i*3} Mei 2026</small><h2>{p[1]}</h2><p>{p[2]}</p><Link href="/berita/forum-aspirasi-mahasiswa">{i===1?'Unduh PDF (1.8 MB)':'Baca selengkapnya'} <ArrowRight/></Link></article>)}</div><nav className="v4-pages"><b>1</b><span>2</span><span>3</span><span>…</span><span>10</span></nav></section></PublicFrame>}

export function V4PublicationDetail(){return <PublicFrame><section className="v4-shell v4-article-layout"><article><div className="v4-article-image" style={{backgroundImage:`url(${activityImages[0]})`}}/><span className="v4-tag">KEGIATAN</span><h1>Forum Aspirasi Mahasiswa Periode 2026–2027: Wadah Dialog dan Penguatan Representasi</h1><small>DPM FIPP UNIMA　·　12 Mei 2026</small><p>DPM FIPP UNIMA menyelenggarakan Forum Aspirasi Mahasiswa sebagai ruang terbuka bagi mahasiswa untuk menyampaikan gagasan, kritik, serta solusi atas isu akademik dan non-akademik.</p><div className="v4-inline-gallery">{activityImages.slice(1,4).map(x=><span key={x} style={{backgroundImage:`url(${x})`}}/>)}</div><p>Dari forum ini diperoleh sejumlah isu prioritas yang akan ditindaklanjuti melalui program kerja dan advokasi kelembagaan. DPM berkomitmen mengawal setiap aspirasi hingga menjadi perubahan nyata.</p><PublicComments slug="forum-aspirasi-mahasiswa"/></article><aside><small>Beranda　›　Publikasi　›　Berita</small><h3>Berita Terkait</h3>{publications.slice(0,3).map((p,i)=><Link href="/berita/forum-aspirasi-mahasiswa" key={p[1]}><span style={{backgroundImage:`url(${activityImages[i]})`}}/><b>{p[1]}</b></Link>)}<h3>Kategori</h3>{['Kegiatan　24','Kajian　18','Pengumuman　12','Berita　9'].map(x=><p key={x}>{x}</p>)}</aside></section></PublicFrame>}

export function V4Ddas(){return <PublicFrame><section className="v4-ddas-intro"><div className="v4-shell"><h1>D-DAS</h1><h2>Data, Dialog, Aspirasi, Solusi.</h2><p>Sampaikan aspirasi Anda dengan mudah dan aman. Setiap aspirasi diproses secara transparan, bertanggung jawab, dan berorientasi pada solusi.</p><div><span><ShieldCheck/><b>Aman & Rahasia</b><small>Identitas Anda dilindungi.</small></span><span><Check/><b>Transparan</b><small>Setiap aspirasi dapat dilacak.</small></span><span><Megaphone/><b>Responsif</b><small>Ditangani oleh pihak terkait.</small></span></div></div></section><section className="v4-shell v4-ddas-grid"><div><DdasForm/></div><div><TrackingForm/><section className="v4-tracking-demo"><header><h2>Hasil Pelacakan <span>Selesai</span></h2><b>D-DAS-2026-AKL3LK8</b></header>{['Masuk — Aspirasi berhasil diterima oleh sistem D-DAS.','Ditinjau — Aspirasi sedang ditinjau oleh tim verifikasi.','Diteruskan — Aspirasi diteruskan ke pihak terkait.','Ditindaklanjuti — Pihak terkait telah memberikan tanggapan.','Selesai — Aspirasi telah diselesaikan.'].map(x=><p key={x}><Check/><span><b>{x.split(' — ')[0]}</b><small>{x.split(' — ')[1]}</small></span></p>)}</section></div></section></PublicFrame>}
